/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpLoginRouteImport } from './routes/sign-up-login'
import { Route as OwnerRouteImport } from './routes/_owner'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGeoRouteImport } from './routes/_authenticated/geo'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedAiHubRouteImport } from './routes/_authenticated/ai-hub'
import { Route as OwnerOwnerX9k2m7IndexRouteImport } from './routes/_owner/owner-x9k2m7.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as OwnerOwnerX9k2m7UsersRouteImport } from './routes/_owner/owner-x9k2m7.users'
import { Route as OwnerOwnerX9k2m7SettingsRouteImport } from './routes/_owner/owner-x9k2m7.settings'
import { Route as OwnerOwnerX9k2m7SecurityRouteImport } from './routes/_owner/owner-x9k2m7.security'
import { Route as OwnerOwnerX9k2m7MarketplaceRouteImport } from './routes/_owner/owner-x9k2m7.marketplace'
import { Route as OwnerOwnerX9k2m7GroupsRouteImport } from './routes/_owner/owner-x9k2m7.groups'
import { Route as OwnerOwnerX9k2m7GeographyRouteImport } from './routes/_owner/owner-x9k2m7.geography'
import { Route as OwnerOwnerX9k2m7FinanceRouteImport } from './routes/_owner/owner-x9k2m7.finance'
import { Route as OwnerOwnerX9k2m7FeaturesRouteImport } from './routes/_owner/owner-x9k2m7.features'
import { Route as OwnerOwnerX9k2m7ContentRouteImport } from './routes/_owner/owner-x9k2m7.content'
import { Route as OwnerOwnerX9k2m7AuditRouteImport } from './routes/_owner/owner-x9k2m7.audit'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminMarketplaceRouteImport } from './routes/_admin/admin.marketplace'
import { Route as AdminAdminContentRouteImport } from './routes/_admin/admin.content'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'
import { Route as AuthenticatedGroupsGroupIdManageRouteImport } from './routes/_authenticated/groups.$groupId.manage'

const SignUpLoginRoute = SignUpLoginRouteImport.update({
  id: '/sign-up-login',
  path: '/sign-up-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeoRoute = AuthenticatedGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiHubRoute = AuthenticatedAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OwnerOwnerX9k2m7IndexRoute = OwnerOwnerX9k2m7IndexRouteImport.update({
  id: '/owner-x9k2m7/',
  path: '/owner-x9k2m7/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerOwnerX9k2m7UsersRoute = OwnerOwnerX9k2m7UsersRouteImport.update({
  id: '/owner-x9k2m7/users',
  path: '/owner-x9k2m7/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7SettingsRoute =
  OwnerOwnerX9k2m7SettingsRouteImport.update({
    id: '/owner-x9k2m7/settings',
    path: '/owner-x9k2m7/settings',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7SecurityRoute =
  OwnerOwnerX9k2m7SecurityRouteImport.update({
    id: '/owner-x9k2m7/security',
    path: '/owner-x9k2m7/security',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7MarketplaceRoute =
  OwnerOwnerX9k2m7MarketplaceRouteImport.update({
    id: '/owner-x9k2m7/marketplace',
    path: '/owner-x9k2m7/marketplace',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7GroupsRoute = OwnerOwnerX9k2m7GroupsRouteImport.update({
  id: '/owner-x9k2m7/groups',
  path: '/owner-x9k2m7/groups',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7GeographyRoute =
  OwnerOwnerX9k2m7GeographyRouteImport.update({
    id: '/owner-x9k2m7/geography',
    path: '/owner-x9k2m7/geography',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7FinanceRoute = OwnerOwnerX9k2m7FinanceRouteImport.update({
  id: '/owner-x9k2m7/finance',
  path: '/owner-x9k2m7/finance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7FeaturesRoute =
  OwnerOwnerX9k2m7FeaturesRouteImport.update({
    id: '/owner-x9k2m7/features',
    path: '/owner-x9k2m7/features',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7ContentRoute = OwnerOwnerX9k2m7ContentRouteImport.update({
  id: '/owner-x9k2m7/content',
  path: '/owner-x9k2m7/content',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7AuditRoute = OwnerOwnerX9k2m7AuditRouteImport.update({
  id: '/owner-x9k2m7/audit',
  path: '/owner-x9k2m7/audit',
  getParentRoute: () => OwnerRoute,
} as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMarketplaceRoute = AdminAdminMarketplaceRouteImport.update({
  id: '/admin/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContentRoute = AdminAdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedGroupsGroupIdManageRoute =
  AuthenticatedGroupsGroupIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-up-login': typeof SignUpLoginRoute
  '/ai-hub': typeof AuthenticatedAiHubRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/geo': typeof AuthenticatedGeoRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/invite': typeof AuthenticatedInviteRoute
  '/live': typeof AuthenticatedLiveRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/content': typeof AdminAdminContentRoute
  '/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/owner-x9k2m7/': typeof OwnerOwnerX9k2m7IndexRoute
  '/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-up-login': typeof SignUpLoginRoute
  '/ai-hub': typeof AuthenticatedAiHubRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/geo': typeof AuthenticatedGeoRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/invite': typeof AuthenticatedInviteRoute
  '/live': typeof AuthenticatedLiveRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/content': typeof AdminAdminContentRoute
  '/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/owner-x9k2m7': typeof OwnerOwnerX9k2m7IndexRoute
  '/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_owner': typeof OwnerRouteWithChildren
  '/sign-up-login': typeof SignUpLoginRoute
  '/_authenticated/ai-hub': typeof AuthenticatedAiHubRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/geo': typeof AuthenticatedGeoRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/content': typeof AdminAdminContentRoute
  '/_admin/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_owner/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/_owner/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/_owner/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/_owner/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/_owner/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/_owner/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/_owner/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/_owner/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/_owner/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/_owner/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_owner/owner-x9k2m7/': typeof OwnerOwnerX9k2m7IndexRoute
  '/_authenticated/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-up-login'
    | '/ai-hub'
    | '/explore'
    | '/feed'
    | '/geo'
    | '/groups'
    | '/invite'
    | '/live'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/stories'
    | '/trade'
    | '/videos'
    | '/voice'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/marketplace'
    | '/admin/users'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/owner-x9k2m7/audit'
    | '/owner-x9k2m7/content'
    | '/owner-x9k2m7/features'
    | '/owner-x9k2m7/finance'
    | '/owner-x9k2m7/geography'
    | '/owner-x9k2m7/groups'
    | '/owner-x9k2m7/marketplace'
    | '/owner-x9k2m7/security'
    | '/owner-x9k2m7/settings'
    | '/owner-x9k2m7/users'
    | '/admin/'
    | '/owner-x9k2m7/'
    | '/groups/$groupId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-up-login'
    | '/ai-hub'
    | '/explore'
    | '/feed'
    | '/geo'
    | '/groups'
    | '/invite'
    | '/live'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/stories'
    | '/trade'
    | '/videos'
    | '/voice'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/marketplace'
    | '/admin/users'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/owner-x9k2m7/audit'
    | '/owner-x9k2m7/content'
    | '/owner-x9k2m7/features'
    | '/owner-x9k2m7/finance'
    | '/owner-x9k2m7/geography'
    | '/owner-x9k2m7/groups'
    | '/owner-x9k2m7/marketplace'
    | '/owner-x9k2m7/security'
    | '/owner-x9k2m7/settings'
    | '/owner-x9k2m7/users'
    | '/admin'
    | '/owner-x9k2m7'
    | '/groups/$groupId/manage'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_owner'
    | '/sign-up-login'
    | '/_authenticated/ai-hub'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/geo'
    | '/_authenticated/groups'
    | '/_authenticated/invite'
    | '/_authenticated/live'
    | '/_authenticated/marketplace'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/stories'
    | '/_authenticated/trade'
    | '/_authenticated/videos'
    | '/_authenticated/voice'
    | '/_admin/admin/analytics'
    | '/_admin/admin/content'
    | '/_admin/admin/marketplace'
    | '/_admin/admin/users'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/messages/$conversationId'
    | '/_owner/owner-x9k2m7/audit'
    | '/_owner/owner-x9k2m7/content'
    | '/_owner/owner-x9k2m7/features'
    | '/_owner/owner-x9k2m7/finance'
    | '/_owner/owner-x9k2m7/geography'
    | '/_owner/owner-x9k2m7/groups'
    | '/_owner/owner-x9k2m7/marketplace'
    | '/_owner/owner-x9k2m7/security'
    | '/_owner/owner-x9k2m7/settings'
    | '/_owner/owner-x9k2m7/users'
    | '/_admin/admin/'
    | '/_owner/owner-x9k2m7/'
    | '/_authenticated/groups/$groupId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  SignUpLoginRoute: typeof SignUpLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up-login': {
      id: '/sign-up-login'
      path: '/sign-up-login'
      fullPath: '/sign-up-login'
      preLoaderRoute: typeof SignUpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/geo': {
      id: '/_authenticated/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof AuthenticatedGeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-hub': {
      id: '/_authenticated/ai-hub'
      path: '/ai-hub'
      fullPath: '/ai-hub'
      preLoaderRoute: typeof AuthenticatedAiHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_owner/owner-x9k2m7/': {
      id: '/_owner/owner-x9k2m7/'
      path: '/owner-x9k2m7'
      fullPath: '/owner-x9k2m7/'
      preLoaderRoute: typeof OwnerOwnerX9k2m7IndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_owner/owner-x9k2m7/users': {
      id: '/_owner/owner-x9k2m7/users'
      path: '/owner-x9k2m7/users'
      fullPath: '/owner-x9k2m7/users'
      preLoaderRoute: typeof OwnerOwnerX9k2m7UsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/settings': {
      id: '/_owner/owner-x9k2m7/settings'
      path: '/owner-x9k2m7/settings'
      fullPath: '/owner-x9k2m7/settings'
      preLoaderRoute: typeof OwnerOwnerX9k2m7SettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/security': {
      id: '/_owner/owner-x9k2m7/security'
      path: '/owner-x9k2m7/security'
      fullPath: '/owner-x9k2m7/security'
      preLoaderRoute: typeof OwnerOwnerX9k2m7SecurityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/marketplace': {
      id: '/_owner/owner-x9k2m7/marketplace'
      path: '/owner-x9k2m7/marketplace'
      fullPath: '/owner-x9k2m7/marketplace'
      preLoaderRoute: typeof OwnerOwnerX9k2m7MarketplaceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/groups': {
      id: '/_owner/owner-x9k2m7/groups'
      path: '/owner-x9k2m7/groups'
      fullPath: '/owner-x9k2m7/groups'
      preLoaderRoute: typeof OwnerOwnerX9k2m7GroupsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/geography': {
      id: '/_owner/owner-x9k2m7/geography'
      path: '/owner-x9k2m7/geography'
      fullPath: '/owner-x9k2m7/geography'
      preLoaderRoute: typeof OwnerOwnerX9k2m7GeographyRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/finance': {
      id: '/_owner/owner-x9k2m7/finance'
      path: '/owner-x9k2m7/finance'
      fullPath: '/owner-x9k2m7/finance'
      preLoaderRoute: typeof OwnerOwnerX9k2m7FinanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/features': {
      id: '/_owner/owner-x9k2m7/features'
      path: '/owner-x9k2m7/features'
      fullPath: '/owner-x9k2m7/features'
      preLoaderRoute: typeof OwnerOwnerX9k2m7FeaturesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/content': {
      id: '/_owner/owner-x9k2m7/content'
      path: '/owner-x9k2m7/content'
      fullPath: '/owner-x9k2m7/content'
      preLoaderRoute: typeof OwnerOwnerX9k2m7ContentRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/audit': {
      id: '/_owner/owner-x9k2m7/audit'
      path: '/owner-x9k2m7/audit'
      fullPath: '/owner-x9k2m7/audit'
      preLoaderRoute: typeof OwnerOwnerX9k2m7AuditRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/marketplace': {
      id: '/_admin/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminAdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/content': {
      id: '/_admin/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminAdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/groups/$groupId/manage': {
      id: '/_authenticated/groups/$groupId/manage'
      path: '/manage'
      fullPath: '/groups/$groupId/manage'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdManageRouteImport
      parentRoute: typeof AuthenticatedGroupsGroupIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminContentRoute: typeof AdminAdminContentRoute
  AdminAdminMarketplaceRoute: typeof AdminAdminMarketplaceRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminContentRoute: AdminAdminContentRoute,
  AdminAdminMarketplaceRoute: AdminAdminMarketplaceRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedGroupsGroupIdRouteChildren {
  AuthenticatedGroupsGroupIdManageRoute: typeof AuthenticatedGroupsGroupIdManageRoute
}

const AuthenticatedGroupsGroupIdRouteChildren: AuthenticatedGroupsGroupIdRouteChildren =
  {
    AuthenticatedGroupsGroupIdManageRoute:
      AuthenticatedGroupsGroupIdManageRoute,
  }

const AuthenticatedGroupsGroupIdRouteWithChildren =
  AuthenticatedGroupsGroupIdRoute._addFileChildren(
    AuthenticatedGroupsGroupIdRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRouteWithChildren
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRouteWithChildren,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAiHubRoute: typeof AuthenticatedAiHubRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGeoRoute: typeof AuthenticatedGeoRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiHubRoute: AuthenticatedAiHubRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGeoRoute: AuthenticatedGeoRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OwnerRouteChildren {
  OwnerOwnerX9k2m7AuditRoute: typeof OwnerOwnerX9k2m7AuditRoute
  OwnerOwnerX9k2m7ContentRoute: typeof OwnerOwnerX9k2m7ContentRoute
  OwnerOwnerX9k2m7FeaturesRoute: typeof OwnerOwnerX9k2m7FeaturesRoute
  OwnerOwnerX9k2m7FinanceRoute: typeof OwnerOwnerX9k2m7FinanceRoute
  OwnerOwnerX9k2m7GeographyRoute: typeof OwnerOwnerX9k2m7GeographyRoute
  OwnerOwnerX9k2m7GroupsRoute: typeof OwnerOwnerX9k2m7GroupsRoute
  OwnerOwnerX9k2m7MarketplaceRoute: typeof OwnerOwnerX9k2m7MarketplaceRoute
  OwnerOwnerX9k2m7SecurityRoute: typeof OwnerOwnerX9k2m7SecurityRoute
  OwnerOwnerX9k2m7SettingsRoute: typeof OwnerOwnerX9k2m7SettingsRoute
  OwnerOwnerX9k2m7UsersRoute: typeof OwnerOwnerX9k2m7UsersRoute
  OwnerOwnerX9k2m7IndexRoute: typeof OwnerOwnerX9k2m7IndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerOwnerX9k2m7AuditRoute: OwnerOwnerX9k2m7AuditRoute,
  OwnerOwnerX9k2m7ContentRoute: OwnerOwnerX9k2m7ContentRoute,
  OwnerOwnerX9k2m7FeaturesRoute: OwnerOwnerX9k2m7FeaturesRoute,
  OwnerOwnerX9k2m7FinanceRoute: OwnerOwnerX9k2m7FinanceRoute,
  OwnerOwnerX9k2m7GeographyRoute: OwnerOwnerX9k2m7GeographyRoute,
  OwnerOwnerX9k2m7GroupsRoute: OwnerOwnerX9k2m7GroupsRoute,
  OwnerOwnerX9k2m7MarketplaceRoute: OwnerOwnerX9k2m7MarketplaceRoute,
  OwnerOwnerX9k2m7SecurityRoute: OwnerOwnerX9k2m7SecurityRoute,
  OwnerOwnerX9k2m7SettingsRoute: OwnerOwnerX9k2m7SettingsRoute,
  OwnerOwnerX9k2m7UsersRoute: OwnerOwnerX9k2m7UsersRoute,
  OwnerOwnerX9k2m7IndexRoute: OwnerOwnerX9k2m7IndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  SignUpLoginRoute: SignUpLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
