/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpLoginRouteImport } from './routes/sign-up-login'
import { Route as OwnerRouteImport } from './routes/_owner'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYoutubeRouteImport } from './routes/_authenticated/youtube'
import { Route as AuthenticatedVoiceRouteImport } from './routes/_authenticated/voice'
import { Route as AuthenticatedVideosRouteImport } from './routes/_authenticated/videos'
import { Route as AuthenticatedTradeRouteImport } from './routes/_authenticated/trade'
import { Route as AuthenticatedTermsOfServiceRouteImport } from './routes/_authenticated/terms-of-service'
import { Route as AuthenticatedStoriesRouteImport } from './routes/_authenticated/stories'
import { Route as AuthenticatedShortVideosRouteImport } from './routes/_authenticated/short-videos'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedPushRouteImport } from './routes/_authenticated/push'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPrivacyPolicyRouteImport } from './routes/_authenticated/privacy-policy'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedPagesGroupsRouteImport } from './routes/_authenticated/pages-groups'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedHnshopRouteImport } from './routes/_authenticated/hnshop'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedGeoRouteImport } from './routes/_authenticated/geo'
import { Route as AuthenticatedGamesRouteImport } from './routes/_authenticated/games'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedEmailDashboardRouteImport } from './routes/_authenticated/email-dashboard'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedAppStoreRouteImport } from './routes/_authenticated/app-store'
import { Route as AuthenticatedAiHubRouteImport } from './routes/_authenticated/ai-hub'
import { Route as AuthenticatedAiAssistantRouteImport } from './routes/_authenticated/ai-assistant'
import { Route as AuthenticatedAdsPromoRouteImport } from './routes/_authenticated/ads-promo'
import { Route as AuthenticatedAdsManagerRouteImport } from './routes/_authenticated/ads-manager'
import { Route as OwnerOwnerX9k2m7IndexRouteImport } from './routes/_owner/owner-x9k2m7.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as OwnerOwnerX9k2m7UsersRouteImport } from './routes/_owner/owner-x9k2m7.users'
import { Route as OwnerOwnerX9k2m7SettingsRouteImport } from './routes/_owner/owner-x9k2m7.settings'
import { Route as OwnerOwnerX9k2m7SecurityRouteImport } from './routes/_owner/owner-x9k2m7.security'
import { Route as OwnerOwnerX9k2m7MarketplaceRouteImport } from './routes/_owner/owner-x9k2m7.marketplace'
import { Route as OwnerOwnerX9k2m7GroupsRouteImport } from './routes/_owner/owner-x9k2m7.groups'
import { Route as OwnerOwnerX9k2m7GeographyRouteImport } from './routes/_owner/owner-x9k2m7.geography'
import { Route as OwnerOwnerX9k2m7FinanceRouteImport } from './routes/_owner/owner-x9k2m7.finance'
import { Route as OwnerOwnerX9k2m7FeaturesRouteImport } from './routes/_owner/owner-x9k2m7.features'
import { Route as OwnerOwnerX9k2m7ContentRouteImport } from './routes/_owner/owner-x9k2m7.content'
import { Route as OwnerOwnerX9k2m7AuditRouteImport } from './routes/_owner/owner-x9k2m7.audit'
import { Route as AuthenticatedWatchIdRouteImport } from './routes/_authenticated/watch.$id'
import { Route as AuthenticatedWatchYtVideoIdRouteImport } from './routes/_authenticated/watch-yt.$videoId'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedGroupsGroupIdRouteImport } from './routes/_authenticated/groups.$groupId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AdminAdminMarketplaceRouteImport } from './routes/_admin/admin.marketplace'
import { Route as AdminAdminContentRouteImport } from './routes/_admin/admin.content'
import { Route as AdminAdminAnalyticsRouteImport } from './routes/_admin/admin.analytics'
import { Route as AuthenticatedGroupsGroupIdManageRouteImport } from './routes/_authenticated/groups.$groupId.manage'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpLoginRoute = SignUpLoginRouteImport.update({
  id: '/sign-up-login',
  path: '/sign-up-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYoutubeRoute = AuthenticatedYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVoiceRoute = AuthenticatedVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideosRoute = AuthenticatedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeRoute = AuthenticatedTradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTermsOfServiceRoute =
  AuthenticatedTermsOfServiceRouteImport.update({
    id: '/terms-of-service',
    path: '/terms-of-service',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStoriesRoute = AuthenticatedStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShortVideosRoute =
  AuthenticatedShortVideosRouteImport.update({
    id: '/short-videos',
    path: '/short-videos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPushRoute = AuthenticatedPushRouteImport.update({
  id: '/push',
  path: '/push',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrivacyPolicyRoute =
  AuthenticatedPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPagesGroupsRoute =
  AuthenticatedPagesGroupsRouteImport.update({
    id: '/pages-groups',
    path: '/pages-groups',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHnshopRoute = AuthenticatedHnshopRouteImport.update({
  id: '/hnshop',
  path: '/hnshop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGeoRoute = AuthenticatedGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGamesRoute = AuthenticatedGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailDashboardRoute =
  AuthenticatedEmailDashboardRouteImport.update({
    id: '/email-dashboard',
    path: '/email-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppStoreRoute = AuthenticatedAppStoreRouteImport.update({
  id: '/app-store',
  path: '/app-store',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiHubRoute = AuthenticatedAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAssistantRoute =
  AuthenticatedAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdsPromoRoute = AuthenticatedAdsPromoRouteImport.update({
  id: '/ads-promo',
  path: '/ads-promo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsManagerRoute = AuthenticatedAdsManagerRouteImport.update({
  id: '/ads-manager',
  path: '/ads-manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OwnerOwnerX9k2m7IndexRoute = OwnerOwnerX9k2m7IndexRouteImport.update({
  id: '/owner-x9k2m7/',
  path: '/owner-x9k2m7/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerOwnerX9k2m7UsersRoute = OwnerOwnerX9k2m7UsersRouteImport.update({
  id: '/owner-x9k2m7/users',
  path: '/owner-x9k2m7/users',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7SettingsRoute =
  OwnerOwnerX9k2m7SettingsRouteImport.update({
    id: '/owner-x9k2m7/settings',
    path: '/owner-x9k2m7/settings',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7SecurityRoute =
  OwnerOwnerX9k2m7SecurityRouteImport.update({
    id: '/owner-x9k2m7/security',
    path: '/owner-x9k2m7/security',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7MarketplaceRoute =
  OwnerOwnerX9k2m7MarketplaceRouteImport.update({
    id: '/owner-x9k2m7/marketplace',
    path: '/owner-x9k2m7/marketplace',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7GroupsRoute = OwnerOwnerX9k2m7GroupsRouteImport.update({
  id: '/owner-x9k2m7/groups',
  path: '/owner-x9k2m7/groups',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7GeographyRoute =
  OwnerOwnerX9k2m7GeographyRouteImport.update({
    id: '/owner-x9k2m7/geography',
    path: '/owner-x9k2m7/geography',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7FinanceRoute = OwnerOwnerX9k2m7FinanceRouteImport.update({
  id: '/owner-x9k2m7/finance',
  path: '/owner-x9k2m7/finance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7FeaturesRoute =
  OwnerOwnerX9k2m7FeaturesRouteImport.update({
    id: '/owner-x9k2m7/features',
    path: '/owner-x9k2m7/features',
    getParentRoute: () => OwnerRoute,
  } as any)
const OwnerOwnerX9k2m7ContentRoute = OwnerOwnerX9k2m7ContentRouteImport.update({
  id: '/owner-x9k2m7/content',
  path: '/owner-x9k2m7/content',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerOwnerX9k2m7AuditRoute = OwnerOwnerX9k2m7AuditRouteImport.update({
  id: '/owner-x9k2m7/audit',
  path: '/owner-x9k2m7/audit',
  getParentRoute: () => OwnerRoute,
} as any)
const AuthenticatedWatchIdRoute = AuthenticatedWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWatchYtVideoIdRoute =
  AuthenticatedWatchYtVideoIdRouteImport.update({
    id: '/watch-yt/$videoId',
    path: '/watch-yt/$videoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedGroupsGroupIdRoute =
  AuthenticatedGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMarketplaceRoute = AdminAdminMarketplaceRouteImport.update({
  id: '/admin/marketplace',
  path: '/admin/marketplace',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminContentRoute = AdminAdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAnalyticsRoute = AdminAdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedGroupsGroupIdManageRoute =
  AuthenticatedGroupsGroupIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedGroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-up-login': typeof SignUpLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ads-manager': typeof AuthenticatedAdsManagerRoute
  '/ads-promo': typeof AuthenticatedAdsPromoRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-hub': typeof AuthenticatedAiHubRoute
  '/app-store': typeof AuthenticatedAppStoreRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/email-dashboard': typeof AuthenticatedEmailDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/games': typeof AuthenticatedGamesRoute
  '/geo': typeof AuthenticatedGeoRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/growth': typeof AuthenticatedGrowthRoute
  '/hnshop': typeof AuthenticatedHnshopRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mail': typeof AuthenticatedMailRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pages-groups': typeof AuthenticatedPagesGroupsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/privacy-policy': typeof AuthenticatedPrivacyPolicyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/push': typeof AuthenticatedPushRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/short-videos': typeof AuthenticatedShortVideosRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/terms-of-service': typeof AuthenticatedTermsOfServiceRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/youtube': typeof AuthenticatedYoutubeRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/content': typeof AdminAdminContentRoute
  '/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/watch-yt/$videoId': typeof AuthenticatedWatchYtVideoIdRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/owner-x9k2m7/': typeof OwnerOwnerX9k2m7IndexRoute
  '/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-up-login': typeof SignUpLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ads-manager': typeof AuthenticatedAdsManagerRoute
  '/ads-promo': typeof AuthenticatedAdsPromoRoute
  '/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/ai-hub': typeof AuthenticatedAiHubRoute
  '/app-store': typeof AuthenticatedAppStoreRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/email-dashboard': typeof AuthenticatedEmailDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/games': typeof AuthenticatedGamesRoute
  '/geo': typeof AuthenticatedGeoRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/growth': typeof AuthenticatedGrowthRoute
  '/hnshop': typeof AuthenticatedHnshopRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/live': typeof AuthenticatedLiveRoute
  '/mail': typeof AuthenticatedMailRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pages-groups': typeof AuthenticatedPagesGroupsRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/privacy-policy': typeof AuthenticatedPrivacyPolicyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/push': typeof AuthenticatedPushRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/short-videos': typeof AuthenticatedShortVideosRoute
  '/stories': typeof AuthenticatedStoriesRoute
  '/terms-of-service': typeof AuthenticatedTermsOfServiceRoute
  '/trade': typeof AuthenticatedTradeRoute
  '/videos': typeof AuthenticatedVideosRoute
  '/voice': typeof AuthenticatedVoiceRoute
  '/youtube': typeof AuthenticatedYoutubeRoute
  '/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/admin/content': typeof AdminAdminContentRoute
  '/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/watch-yt/$videoId': typeof AuthenticatedWatchYtVideoIdRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/owner-x9k2m7': typeof OwnerOwnerX9k2m7IndexRoute
  '/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_owner': typeof OwnerRouteWithChildren
  '/sign-up-login': typeof SignUpLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/ads-manager': typeof AuthenticatedAdsManagerRoute
  '/_authenticated/ads-promo': typeof AuthenticatedAdsPromoRoute
  '/_authenticated/ai-assistant': typeof AuthenticatedAiAssistantRoute
  '/_authenticated/ai-hub': typeof AuthenticatedAiHubRoute
  '/_authenticated/app-store': typeof AuthenticatedAppStoreRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/email-dashboard': typeof AuthenticatedEmailDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/games': typeof AuthenticatedGamesRoute
  '/_authenticated/geo': typeof AuthenticatedGeoRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/hnshop': typeof AuthenticatedHnshopRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pages-groups': typeof AuthenticatedPagesGroupsRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/privacy-policy': typeof AuthenticatedPrivacyPolicyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/push': typeof AuthenticatedPushRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/short-videos': typeof AuthenticatedShortVideosRoute
  '/_authenticated/stories': typeof AuthenticatedStoriesRoute
  '/_authenticated/terms-of-service': typeof AuthenticatedTermsOfServiceRoute
  '/_authenticated/trade': typeof AuthenticatedTradeRoute
  '/_authenticated/videos': typeof AuthenticatedVideosRoute
  '/_authenticated/voice': typeof AuthenticatedVoiceRoute
  '/_authenticated/youtube': typeof AuthenticatedYoutubeRoute
  '/_admin/admin/analytics': typeof AdminAdminAnalyticsRoute
  '/_admin/admin/content': typeof AdminAdminContentRoute
  '/_admin/admin/marketplace': typeof AdminAdminMarketplaceRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/groups/$groupId': typeof AuthenticatedGroupsGroupIdRouteWithChildren
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/watch-yt/$videoId': typeof AuthenticatedWatchYtVideoIdRoute
  '/_authenticated/watch/$id': typeof AuthenticatedWatchIdRoute
  '/_owner/owner-x9k2m7/audit': typeof OwnerOwnerX9k2m7AuditRoute
  '/_owner/owner-x9k2m7/content': typeof OwnerOwnerX9k2m7ContentRoute
  '/_owner/owner-x9k2m7/features': typeof OwnerOwnerX9k2m7FeaturesRoute
  '/_owner/owner-x9k2m7/finance': typeof OwnerOwnerX9k2m7FinanceRoute
  '/_owner/owner-x9k2m7/geography': typeof OwnerOwnerX9k2m7GeographyRoute
  '/_owner/owner-x9k2m7/groups': typeof OwnerOwnerX9k2m7GroupsRoute
  '/_owner/owner-x9k2m7/marketplace': typeof OwnerOwnerX9k2m7MarketplaceRoute
  '/_owner/owner-x9k2m7/security': typeof OwnerOwnerX9k2m7SecurityRoute
  '/_owner/owner-x9k2m7/settings': typeof OwnerOwnerX9k2m7SettingsRoute
  '/_owner/owner-x9k2m7/users': typeof OwnerOwnerX9k2m7UsersRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_owner/owner-x9k2m7/': typeof OwnerOwnerX9k2m7IndexRoute
  '/_authenticated/groups/$groupId/manage': typeof AuthenticatedGroupsGroupIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-up-login'
    | '/sitemap.xml'
    | '/ads-manager'
    | '/ads-promo'
    | '/ai-assistant'
    | '/ai-hub'
    | '/app-store'
    | '/bookmarks'
    | '/email-dashboard'
    | '/explore'
    | '/feed'
    | '/games'
    | '/geo'
    | '/groups'
    | '/growth'
    | '/hnshop'
    | '/invite'
    | '/live'
    | '/mail'
    | '/marketplace'
    | '/messages'
    | '/monitoring'
    | '/notifications'
    | '/pages-groups'
    | '/preferences'
    | '/privacy-policy'
    | '/profile'
    | '/push'
    | '/reels'
    | '/search'
    | '/settings'
    | '/short-videos'
    | '/stories'
    | '/terms-of-service'
    | '/trade'
    | '/videos'
    | '/voice'
    | '/youtube'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/marketplace'
    | '/admin/users'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/watch-yt/$videoId'
    | '/watch/$id'
    | '/owner-x9k2m7/audit'
    | '/owner-x9k2m7/content'
    | '/owner-x9k2m7/features'
    | '/owner-x9k2m7/finance'
    | '/owner-x9k2m7/geography'
    | '/owner-x9k2m7/groups'
    | '/owner-x9k2m7/marketplace'
    | '/owner-x9k2m7/security'
    | '/owner-x9k2m7/settings'
    | '/owner-x9k2m7/users'
    | '/admin/'
    | '/owner-x9k2m7/'
    | '/groups/$groupId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-up-login'
    | '/sitemap.xml'
    | '/ads-manager'
    | '/ads-promo'
    | '/ai-assistant'
    | '/ai-hub'
    | '/app-store'
    | '/bookmarks'
    | '/email-dashboard'
    | '/explore'
    | '/feed'
    | '/games'
    | '/geo'
    | '/groups'
    | '/growth'
    | '/hnshop'
    | '/invite'
    | '/live'
    | '/mail'
    | '/marketplace'
    | '/messages'
    | '/monitoring'
    | '/notifications'
    | '/pages-groups'
    | '/preferences'
    | '/privacy-policy'
    | '/profile'
    | '/push'
    | '/reels'
    | '/search'
    | '/settings'
    | '/short-videos'
    | '/stories'
    | '/terms-of-service'
    | '/trade'
    | '/videos'
    | '/voice'
    | '/youtube'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/marketplace'
    | '/admin/users'
    | '/groups/$groupId'
    | '/messages/$conversationId'
    | '/watch-yt/$videoId'
    | '/watch/$id'
    | '/owner-x9k2m7/audit'
    | '/owner-x9k2m7/content'
    | '/owner-x9k2m7/features'
    | '/owner-x9k2m7/finance'
    | '/owner-x9k2m7/geography'
    | '/owner-x9k2m7/groups'
    | '/owner-x9k2m7/marketplace'
    | '/owner-x9k2m7/security'
    | '/owner-x9k2m7/settings'
    | '/owner-x9k2m7/users'
    | '/admin'
    | '/owner-x9k2m7'
    | '/groups/$groupId/manage'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/_owner'
    | '/sign-up-login'
    | '/sitemap.xml'
    | '/_authenticated/ads-manager'
    | '/_authenticated/ads-promo'
    | '/_authenticated/ai-assistant'
    | '/_authenticated/ai-hub'
    | '/_authenticated/app-store'
    | '/_authenticated/bookmarks'
    | '/_authenticated/email-dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/feed'
    | '/_authenticated/games'
    | '/_authenticated/geo'
    | '/_authenticated/groups'
    | '/_authenticated/growth'
    | '/_authenticated/hnshop'
    | '/_authenticated/invite'
    | '/_authenticated/live'
    | '/_authenticated/mail'
    | '/_authenticated/marketplace'
    | '/_authenticated/messages'
    | '/_authenticated/monitoring'
    | '/_authenticated/notifications'
    | '/_authenticated/pages-groups'
    | '/_authenticated/preferences'
    | '/_authenticated/privacy-policy'
    | '/_authenticated/profile'
    | '/_authenticated/push'
    | '/_authenticated/reels'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/short-videos'
    | '/_authenticated/stories'
    | '/_authenticated/terms-of-service'
    | '/_authenticated/trade'
    | '/_authenticated/videos'
    | '/_authenticated/voice'
    | '/_authenticated/youtube'
    | '/_admin/admin/analytics'
    | '/_admin/admin/content'
    | '/_admin/admin/marketplace'
    | '/_admin/admin/users'
    | '/_authenticated/groups/$groupId'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/watch-yt/$videoId'
    | '/_authenticated/watch/$id'
    | '/_owner/owner-x9k2m7/audit'
    | '/_owner/owner-x9k2m7/content'
    | '/_owner/owner-x9k2m7/features'
    | '/_owner/owner-x9k2m7/finance'
    | '/_owner/owner-x9k2m7/geography'
    | '/_owner/owner-x9k2m7/groups'
    | '/_owner/owner-x9k2m7/marketplace'
    | '/_owner/owner-x9k2m7/security'
    | '/_owner/owner-x9k2m7/settings'
    | '/_owner/owner-x9k2m7/users'
    | '/_admin/admin/'
    | '/_owner/owner-x9k2m7/'
    | '/_authenticated/groups/$groupId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OwnerRoute: typeof OwnerRouteWithChildren
  SignUpLoginRoute: typeof SignUpLoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up-login': {
      id: '/sign-up-login'
      path: '/sign-up-login'
      fullPath: '/sign-up-login'
      preLoaderRoute: typeof SignUpLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/youtube': {
      id: '/_authenticated/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof AuthenticatedYoutubeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/voice': {
      id: '/_authenticated/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof AuthenticatedVoiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos': {
      id: '/_authenticated/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof AuthenticatedVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade': {
      id: '/_authenticated/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof AuthenticatedTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terms-of-service': {
      id: '/_authenticated/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof AuthenticatedTermsOfServiceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stories': {
      id: '/_authenticated/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof AuthenticatedStoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/short-videos': {
      id: '/_authenticated/short-videos'
      path: '/short-videos'
      fullPath: '/short-videos'
      preLoaderRoute: typeof AuthenticatedShortVideosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/push': {
      id: '/_authenticated/push'
      path: '/push'
      fullPath: '/push'
      preLoaderRoute: typeof AuthenticatedPushRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/privacy-policy': {
      id: '/_authenticated/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof AuthenticatedPrivacyPolicyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pages-groups': {
      id: '/_authenticated/pages-groups'
      path: '/pages-groups'
      fullPath: '/pages-groups'
      preLoaderRoute: typeof AuthenticatedPagesGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hnshop': {
      id: '/_authenticated/hnshop'
      path: '/hnshop'
      fullPath: '/hnshop'
      preLoaderRoute: typeof AuthenticatedHnshopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/geo': {
      id: '/_authenticated/geo'
      path: '/geo'
      fullPath: '/geo'
      preLoaderRoute: typeof AuthenticatedGeoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/games': {
      id: '/_authenticated/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AuthenticatedGamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-dashboard': {
      id: '/_authenticated/email-dashboard'
      path: '/email-dashboard'
      fullPath: '/email-dashboard'
      preLoaderRoute: typeof AuthenticatedEmailDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-store': {
      id: '/_authenticated/app-store'
      path: '/app-store'
      fullPath: '/app-store'
      preLoaderRoute: typeof AuthenticatedAppStoreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-hub': {
      id: '/_authenticated/ai-hub'
      path: '/ai-hub'
      fullPath: '/ai-hub'
      preLoaderRoute: typeof AuthenticatedAiHubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-assistant': {
      id: '/_authenticated/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AuthenticatedAiAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads-promo': {
      id: '/_authenticated/ads-promo'
      path: '/ads-promo'
      fullPath: '/ads-promo'
      preLoaderRoute: typeof AuthenticatedAdsPromoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads-manager': {
      id: '/_authenticated/ads-manager'
      path: '/ads-manager'
      fullPath: '/ads-manager'
      preLoaderRoute: typeof AuthenticatedAdsManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_owner/owner-x9k2m7/': {
      id: '/_owner/owner-x9k2m7/'
      path: '/owner-x9k2m7'
      fullPath: '/owner-x9k2m7/'
      preLoaderRoute: typeof OwnerOwnerX9k2m7IndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_owner/owner-x9k2m7/users': {
      id: '/_owner/owner-x9k2m7/users'
      path: '/owner-x9k2m7/users'
      fullPath: '/owner-x9k2m7/users'
      preLoaderRoute: typeof OwnerOwnerX9k2m7UsersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/settings': {
      id: '/_owner/owner-x9k2m7/settings'
      path: '/owner-x9k2m7/settings'
      fullPath: '/owner-x9k2m7/settings'
      preLoaderRoute: typeof OwnerOwnerX9k2m7SettingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/security': {
      id: '/_owner/owner-x9k2m7/security'
      path: '/owner-x9k2m7/security'
      fullPath: '/owner-x9k2m7/security'
      preLoaderRoute: typeof OwnerOwnerX9k2m7SecurityRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/marketplace': {
      id: '/_owner/owner-x9k2m7/marketplace'
      path: '/owner-x9k2m7/marketplace'
      fullPath: '/owner-x9k2m7/marketplace'
      preLoaderRoute: typeof OwnerOwnerX9k2m7MarketplaceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/groups': {
      id: '/_owner/owner-x9k2m7/groups'
      path: '/owner-x9k2m7/groups'
      fullPath: '/owner-x9k2m7/groups'
      preLoaderRoute: typeof OwnerOwnerX9k2m7GroupsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/geography': {
      id: '/_owner/owner-x9k2m7/geography'
      path: '/owner-x9k2m7/geography'
      fullPath: '/owner-x9k2m7/geography'
      preLoaderRoute: typeof OwnerOwnerX9k2m7GeographyRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/finance': {
      id: '/_owner/owner-x9k2m7/finance'
      path: '/owner-x9k2m7/finance'
      fullPath: '/owner-x9k2m7/finance'
      preLoaderRoute: typeof OwnerOwnerX9k2m7FinanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/features': {
      id: '/_owner/owner-x9k2m7/features'
      path: '/owner-x9k2m7/features'
      fullPath: '/owner-x9k2m7/features'
      preLoaderRoute: typeof OwnerOwnerX9k2m7FeaturesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/content': {
      id: '/_owner/owner-x9k2m7/content'
      path: '/owner-x9k2m7/content'
      fullPath: '/owner-x9k2m7/content'
      preLoaderRoute: typeof OwnerOwnerX9k2m7ContentRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/owner-x9k2m7/audit': {
      id: '/_owner/owner-x9k2m7/audit'
      path: '/owner-x9k2m7/audit'
      fullPath: '/owner-x9k2m7/audit'
      preLoaderRoute: typeof OwnerOwnerX9k2m7AuditRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_authenticated/watch/$id': {
      id: '/_authenticated/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AuthenticatedWatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/watch-yt/$videoId': {
      id: '/_authenticated/watch-yt/$videoId'
      path: '/watch-yt/$videoId'
      fullPath: '/watch-yt/$videoId'
      preLoaderRoute: typeof AuthenticatedWatchYtVideoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/groups/$groupId': {
      id: '/_authenticated/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/marketplace': {
      id: '/_admin/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AdminAdminMarketplaceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/content': {
      id: '/_admin/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminAdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/analytics': {
      id: '/_admin/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/groups/$groupId/manage': {
      id: '/_authenticated/groups/$groupId/manage'
      path: '/manage'
      fullPath: '/groups/$groupId/manage'
      preLoaderRoute: typeof AuthenticatedGroupsGroupIdManageRouteImport
      parentRoute: typeof AuthenticatedGroupsGroupIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAnalyticsRoute: typeof AdminAdminAnalyticsRoute
  AdminAdminContentRoute: typeof AdminAdminContentRoute
  AdminAdminMarketplaceRoute: typeof AdminAdminMarketplaceRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAnalyticsRoute: AdminAdminAnalyticsRoute,
  AdminAdminContentRoute: AdminAdminContentRoute,
  AdminAdminMarketplaceRoute: AdminAdminMarketplaceRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedGroupsGroupIdRouteChildren {
  AuthenticatedGroupsGroupIdManageRoute: typeof AuthenticatedGroupsGroupIdManageRoute
}

const AuthenticatedGroupsGroupIdRouteChildren: AuthenticatedGroupsGroupIdRouteChildren =
  {
    AuthenticatedGroupsGroupIdManageRoute:
      AuthenticatedGroupsGroupIdManageRoute,
  }

const AuthenticatedGroupsGroupIdRouteWithChildren =
  AuthenticatedGroupsGroupIdRoute._addFileChildren(
    AuthenticatedGroupsGroupIdRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsGroupIdRoute: typeof AuthenticatedGroupsGroupIdRouteWithChildren
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsGroupIdRoute: AuthenticatedGroupsGroupIdRouteWithChildren,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdsManagerRoute: typeof AuthenticatedAdsManagerRoute
  AuthenticatedAdsPromoRoute: typeof AuthenticatedAdsPromoRoute
  AuthenticatedAiAssistantRoute: typeof AuthenticatedAiAssistantRoute
  AuthenticatedAiHubRoute: typeof AuthenticatedAiHubRoute
  AuthenticatedAppStoreRoute: typeof AuthenticatedAppStoreRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedEmailDashboardRoute: typeof AuthenticatedEmailDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGamesRoute: typeof AuthenticatedGamesRoute
  AuthenticatedGeoRoute: typeof AuthenticatedGeoRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedHnshopRoute: typeof AuthenticatedHnshopRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPagesGroupsRoute: typeof AuthenticatedPagesGroupsRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedPrivacyPolicyRoute: typeof AuthenticatedPrivacyPolicyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPushRoute: typeof AuthenticatedPushRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShortVideosRoute: typeof AuthenticatedShortVideosRoute
  AuthenticatedStoriesRoute: typeof AuthenticatedStoriesRoute
  AuthenticatedTermsOfServiceRoute: typeof AuthenticatedTermsOfServiceRoute
  AuthenticatedTradeRoute: typeof AuthenticatedTradeRoute
  AuthenticatedVideosRoute: typeof AuthenticatedVideosRoute
  AuthenticatedVoiceRoute: typeof AuthenticatedVoiceRoute
  AuthenticatedYoutubeRoute: typeof AuthenticatedYoutubeRoute
  AuthenticatedWatchYtVideoIdRoute: typeof AuthenticatedWatchYtVideoIdRoute
  AuthenticatedWatchIdRoute: typeof AuthenticatedWatchIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdsManagerRoute: AuthenticatedAdsManagerRoute,
  AuthenticatedAdsPromoRoute: AuthenticatedAdsPromoRoute,
  AuthenticatedAiAssistantRoute: AuthenticatedAiAssistantRoute,
  AuthenticatedAiHubRoute: AuthenticatedAiHubRoute,
  AuthenticatedAppStoreRoute: AuthenticatedAppStoreRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedEmailDashboardRoute: AuthenticatedEmailDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGamesRoute: AuthenticatedGamesRoute,
  AuthenticatedGeoRoute: AuthenticatedGeoRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedHnshopRoute: AuthenticatedHnshopRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPagesGroupsRoute: AuthenticatedPagesGroupsRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedPrivacyPolicyRoute: AuthenticatedPrivacyPolicyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPushRoute: AuthenticatedPushRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShortVideosRoute: AuthenticatedShortVideosRoute,
  AuthenticatedStoriesRoute: AuthenticatedStoriesRoute,
  AuthenticatedTermsOfServiceRoute: AuthenticatedTermsOfServiceRoute,
  AuthenticatedTradeRoute: AuthenticatedTradeRoute,
  AuthenticatedVideosRoute: AuthenticatedVideosRoute,
  AuthenticatedVoiceRoute: AuthenticatedVoiceRoute,
  AuthenticatedYoutubeRoute: AuthenticatedYoutubeRoute,
  AuthenticatedWatchYtVideoIdRoute: AuthenticatedWatchYtVideoIdRoute,
  AuthenticatedWatchIdRoute: AuthenticatedWatchIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OwnerRouteChildren {
  OwnerOwnerX9k2m7AuditRoute: typeof OwnerOwnerX9k2m7AuditRoute
  OwnerOwnerX9k2m7ContentRoute: typeof OwnerOwnerX9k2m7ContentRoute
  OwnerOwnerX9k2m7FeaturesRoute: typeof OwnerOwnerX9k2m7FeaturesRoute
  OwnerOwnerX9k2m7FinanceRoute: typeof OwnerOwnerX9k2m7FinanceRoute
  OwnerOwnerX9k2m7GeographyRoute: typeof OwnerOwnerX9k2m7GeographyRoute
  OwnerOwnerX9k2m7GroupsRoute: typeof OwnerOwnerX9k2m7GroupsRoute
  OwnerOwnerX9k2m7MarketplaceRoute: typeof OwnerOwnerX9k2m7MarketplaceRoute
  OwnerOwnerX9k2m7SecurityRoute: typeof OwnerOwnerX9k2m7SecurityRoute
  OwnerOwnerX9k2m7SettingsRoute: typeof OwnerOwnerX9k2m7SettingsRoute
  OwnerOwnerX9k2m7UsersRoute: typeof OwnerOwnerX9k2m7UsersRoute
  OwnerOwnerX9k2m7IndexRoute: typeof OwnerOwnerX9k2m7IndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerOwnerX9k2m7AuditRoute: OwnerOwnerX9k2m7AuditRoute,
  OwnerOwnerX9k2m7ContentRoute: OwnerOwnerX9k2m7ContentRoute,
  OwnerOwnerX9k2m7FeaturesRoute: OwnerOwnerX9k2m7FeaturesRoute,
  OwnerOwnerX9k2m7FinanceRoute: OwnerOwnerX9k2m7FinanceRoute,
  OwnerOwnerX9k2m7GeographyRoute: OwnerOwnerX9k2m7GeographyRoute,
  OwnerOwnerX9k2m7GroupsRoute: OwnerOwnerX9k2m7GroupsRoute,
  OwnerOwnerX9k2m7MarketplaceRoute: OwnerOwnerX9k2m7MarketplaceRoute,
  OwnerOwnerX9k2m7SecurityRoute: OwnerOwnerX9k2m7SecurityRoute,
  OwnerOwnerX9k2m7SettingsRoute: OwnerOwnerX9k2m7SettingsRoute,
  OwnerOwnerX9k2m7UsersRoute: OwnerOwnerX9k2m7UsersRoute,
  OwnerOwnerX9k2m7IndexRoute: OwnerOwnerX9k2m7IndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OwnerRoute: OwnerRouteWithChildren,
  SignUpLoginRoute: SignUpLoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
